version: '3'

services:
  web-app:
    container_name: react-web-app
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - '3000:3000'
    volumes:
      - /app/node_modules 
      - .:/app